package aitrailers

import "testing"

// leaked é o rodapé como ele chegou ao corpo de um pull request deste
// repositório: emoji na frente, nome da ferramenta dentro de um link, e o
// link da sessão numa linha sozinha logo abaixo.
const leaked = "O documento da listagem de working trees.\r\n" +
	"\r\n" +
	"🤖 Generated with [Claude Code](https://claude.com/claude-code)\r\n" +
	"\r\n" +
	"https://claude.ai/code/session_01VW6gJjPdk4zCJMLTUJjQ6k\r\n"

func TestAttributionsFindsTheLooseFooter(t *testing.T) {
	found := Attributions(leaked)

	if len(found) == 0 {
		t.Fatal("o rodapé solto é a forma que vazou, e é a que o bloco de trailer não pega")
	}
	if found[0].Tool != "Claude Code" {
		t.Errorf("ferramenta = %q, queria Claude Code", found[0].Tool)
	}
}

func TestAttributionsKeepsTheLineThatMatched(t *testing.T) {
	found := Attributions(leaked)

	wanted := "🤖 Generated with [Claude Code](https://claude.com/claude-code)"
	if found[0].Line != wanted {
		t.Errorf("linha = %q, queria %q; sem a evidência a saída pede confiança", found[0].Line, wanted)
	}
}

func TestAttributionsSurvivesTheCarriageReturn(t *testing.T) {
	if len(Attributions(leaked)) != 2 {
		t.Errorf("achados = %+v; corpo de pull request vem com CRLF, e o \\r não pode virar parte da linha", Attributions(leaked))
	}
}

func TestAttributionsFindsTheSessionLink(t *testing.T) {
	found := Attributions("https://claude.ai/code/session_01VW6gJjPdk4zCJMLTUJjQ6k")

	if len(found) != 1 {
		t.Fatalf("achados = %+v; o link da sessão vem sem chave nenhuma na frente, e nenhuma outra regra o pegaria", found)
	}
	if found[0].Tool != "Claude Code" {
		t.Errorf("ferramenta = %q, queria Claude Code", found[0].Tool)
	}
}

func TestAttributionsIgnoresTheFooterQuotedInTheMiddleOfASentence(t *testing.T) {
	prose := "- Uma exclusão que saiu de graça: um rodapé solto como " +
		`"Generated with Claude Code" não aparece em %(trailers:only).`

	if found := Attributions(prose); len(found) != 0 {
		t.Errorf("achados = %+v; citar não é atribuir, e este texto é de um documento sobre a própria detecção", found)
	}
}

func TestAttributionsFindsTheSignatureAnywhereInTheBody(t *testing.T) {
	found := Attributions("Fecha o #12.\n\nCo-Authored-By: Claude <noreply@anthropic.com>")

	if len(found) != 1 {
		t.Fatalf("achados = %+v; a assinatura no corpo não está em bloco de trailer nenhum, mas é a mesma assinatura", found)
	}
	if found[0].Tool != "Claude Code" {
		t.Errorf("ferramenta = %q, queria Claude Code", found[0].Tool)
	}
}

func TestAttributionsFindsTheCopilotSignature(t *testing.T) {
	found := Attributions("Co-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>")

	if len(found) != 1 || found[0].Tool != "GitHub Copilot" {
		t.Errorf("achados = %+v, queria a assinatura do Copilot", found)
	}
}

func TestAttributionsNamesTheToolTheSameWayTheSignatureDoes(t *testing.T) {
	signature, err := Signature("claude")
	if err != nil {
		t.Fatalf("nao esperava erro, veio %v", err)
	}

	found := Attributions("🤖 Generated with Claude Code")

	if len(found) != 1 || found[0].Tool != signature.Tool {
		t.Errorf("achados = %+v; detectar em prosa e fabricar trailer têm de dizer o mesmo nome, %q", found, signature.Tool)
	}
}

func TestAttributionsOfATextWithoutAnything(t *testing.T) {
	if found := Attributions("Especifica a listagem de working trees.\n\nSem novidade nenhuma."); found != nil {
		t.Errorf("achados = %+v, queria nenhum", found)
	}
}

func TestAttributionsOfAnEmptyText(t *testing.T) {
	if found := Attributions(""); found != nil {
		t.Errorf("achados = %+v; corpo vazio é o caso mais comum, e não pode ser achado", found)
	}
}

func TestAttributionsFindsTheFooterUnderMarkdownDecoration(t *testing.T) {
	for _, decorated := range []string{
		"**Generated with Claude Code**",
		"> Generated with Claude Code",
		"- Generated with Claude Code",
		"   Generated with Claude Code",
	} {
		if found := Attributions(decorated); len(found) != 1 {
			t.Errorf("%q: achados = %+v; decoração de Markdown na frente não desfaz o rodapé", decorated, found)
		}
	}
}

func TestAttributionsIgnoresTheFooterOfAToolItDoesNotKnow(t *testing.T) {
	if found := Attributions("Generated with uma ferramenta qualquer"); len(found) != 0 {
		t.Errorf("achados = %+v; a abertura sozinha não nomeia ferramenta nenhuma", found)
	}
}

// TestAttributionsFindsTheFooterTheServerAppends usa o rodapé como ele foi
// anexado ao corpo do #38 deste repositório: itálico de Markdown em volta,
// "Generated by" no lugar de "Generated with", e o link do produto sem
// identificador de sessão nenhum. A primeira versão desta detecção conhecia
// só o "with" e deixaria este passar inteiro.
func TestAttributionsFindsTheFooterTheServerAppends(t *testing.T) {
	appended := "_Generated by [Claude Code](https://claude.ai/code)_"

	found := Attributions(appended)

	if len(found) != 1 {
		t.Fatalf("achados = %+v; é o rodapé que o servidor anexa, e é o que vazou", found)
	}
	if found[0].Tool != "Claude Code" {
		t.Errorf("ferramenta = %q, queria Claude Code", found[0].Tool)
	}
}

func TestAttributionsFindsTheFooterWithTheSessionLink(t *testing.T) {
	appended := "_Generated by [Claude Code](https://claude.ai/code/session_01VW6gJjPdk4zCJMLTUJjQ6k)_"

	if found := Attributions(appended); len(found) != 1 {
		t.Errorf("achados = %+v; a variante com sessão é a mesma atribuição", found)
	}
}
