package aitrailers

import (
	"strings"
	"unicode"
)

// Attribution é uma marca de autoria de IA achada em texto corrido — título e
// corpo de pull request, onde não há bloco de trailer nenhum para o git
// interpretar. Line é a linha que casou, aparada: a saída mostra a evidência
// em vez de pedir confiança, porque quem lê é que decide se é atribuição ou
// menção.
type Attribution struct {
	Tool string
	Line string
}

// footerOpenings são os começos de rodapé de atribuição vistos na prática,
// os dois medidos no corpo dos pull requests deste repositório: o
// "Generated with" que acompanha o link do produto e o "Generated by" que
// acompanha o link da sessão. Cresce por observação, como a lista de
// detect.go, não por suposição — a segunda entrou depois de a primeira
// deixar passar um rodapé de verdade.
var footerOpenings = []string{"generated with", "generated by"}

// products liga cada marca textual ao mesmo nome de ferramenta que
// signature.go e detect.go já usam, para as três formas de detecção nunca
// divergirem sobre como uma ferramenta se chama.
//
// name aparece no rodapé, e só conta ancorado no começo da linha. anywhere
// é o que só uma máquina escreve — o link da sessão e o do produto —, e
// conta em qualquer posição, porque não vem com abertura nenhuma na frente.
var products = []struct {
	tool     string
	names    []string
	anywhere []string
}{
	{
		tool:     "Claude Code",
		names:    []string{"claude code"},
		anywhere: []string{"claude.ai/code", "claude.com/claude-code"},
	},
	{
		tool:  "GitHub Copilot",
		names: []string{"github copilot"},
	},
}

// Attributions devolve as marcas de autoria de IA de um texto que não é bloco
// de trailer de commit. Três formas, cada uma vista antes de virar regra:
//
//   - a linha "chave: valor" que bate numa assinatura conhecida, em qualquer
//     posição do texto — é o mesmo tool() que o histórico usa, e por isso
//     commit e pull request nunca divergem sobre o que é assinatura;
//   - o rodapé solto, linha que abre em "Generated with" e nomeia uma
//     ferramenta conhecida — a forma que o git interpret-trailers não
//     reconhece, e que por isso o List nunca vê;
//   - o link de sessão ou de produto, em qualquer posição da linha.
//
// O rodapé casa ancorado no começo da linha, depois de descartada a
// decoração: é o que separa atribuir de citar. Uma frase que menciona
// "Generated with Claude Code" no meio não casa; a mesma frase abrindo a
// linha casa, e é falso positivo aceito de propósito. Este pacote só reporta
// o que achou — quem decide o que fazer é quem lê.
func Attributions(text string) []Attribution {
	var found []Attribution

	for _, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(strings.TrimSuffix(raw, "\r"))
		if line == "" {
			continue
		}

		if name, matched := attribution(line); matched {
			found = append(found, Attribution{Tool: name, Line: line})
		}
	}

	return found
}

func attribution(line string) (string, bool) {
	if key, value, split := strings.Cut(line, ": "); split {
		if name, matched := tool(key, value); matched {
			return name, true
		}
	}

	lowered := strings.ToLower(line)

	for _, candidate := range products {
		for _, marker := range candidate.anywhere {
			if strings.Contains(lowered, marker) {
				return candidate.tool, true
			}
		}
	}

	if !opens(undecorated(lowered)) {
		return "", false
	}

	for _, candidate := range products {
		for _, name := range candidate.names {
			if strings.Contains(lowered, name) {
				return candidate.tool, true
			}
		}
	}

	return "", false
}

func opens(line string) bool {
	for _, opening := range footerOpenings {
		if strings.HasPrefix(line, opening) {
			return true
		}
	}

	return false
}

// undecorated descarta o que vem antes da primeira letra da linha — espaço,
// marcador de lista, asterisco de negrito, citação, emoji. O rodapé que
// vazou neste repositório abria com um emoji e um espaço, e sem isso a
// âncora no começo da linha não o pegaria.
func undecorated(line string) string {
	return strings.TrimLeftFunc(line, func(letter rune) bool {
		return !unicode.IsLetter(letter)
	})
}
